---
kind: Service
apiVersion: v1
metadata:
  name: lb-freeradius
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  ports:
    - name: 'radius'
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: 'radius-acct'
      protocol: UDP
      port: 1813
      targetPort: 1813
  selector:
    name: freeradius
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
